import React, { useState } from 'react'
import { LanguageContext } from './languageContext.js'

const translations = {
  es: {
    // Navigation
    home: 'Inicio',
    about: 'Acerca de',
    services: 'Servicios',
    cart: 'Carrito',
    orders: 'Pedidos',
    adminPanel: 'Panel Admin',
    logout: 'Cerrar Sesión',
    adminLogin: 'Iniciar Sesión',
    
    // Product List
    ourProducts: 'Nuestros Productos',
    loadingProducts: 'Cargando productos...',
    viewDetails: 'Ver',
    
    // Cart
    shoppingCart: 'Carrito de Compras',
    loadingCart: 'Cargando carrito...',
    emptyCart: 'Tu carrito está vacío',
    continueShopping: 'Continuar Comprando',
    remove: 'Eliminar',
    orderSummary: 'Resumen del Pedido',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    free: 'Gratis',
    calculatedAtCheckout: 'Se calcula en el checkout',
    bulkDiscount: 'Descuento por Volumen',
    bulkDiscountApplied: '🎉 ¡Descuento del {percent}% aplicado por comprar {quantity}+ artículos!',
    buyXAndSave: 'Compra {quantity}+ y ahorra {percent}%',
    savePercent: 'Ahorra {percent}%',
    discountAppliedForQuantity: 'Descuento del {percent}% aplicado por comprar {quantity} artículos',
    total: 'Total',
    checkout: 'Finalizar Compra',
    clearCart: 'Vaciar Carrito',
    
    // Categories
    allProducts: 'Todos los Productos',
    more: 'más',
    showLess: 'Ver menos',
    chargers: 'Cargadores',
    laptops: 'Laptops',
    ipads: 'iPads',
    accessories: 'Accesorios',
    other: 'Otros',
    noCategories: 'No hay categorías disponibles',

    // Services page
    servicesTitle: 'Desarrollo Web y Software',
    servicesSubtitle: 'Creamos sitios web, tiendas en línea y aplicaciones a la medida. Cuéntanos tu proyecto y te enviamos una cotización sin compromiso.',
    servicesWhatWeBuild: 'Qué desarrollamos',
    service_webDev_title: 'Páginas web',
    service_webDev_desc: 'Sitios corporativos, portafolios y landing pages optimizados para móvil y SEO.',
    service_webDev_feature1: 'Diseño responsive (móvil y escritorio)',
    service_webDev_feature2: 'Optimización SEO básica',
    service_webDev_feature3: 'Formulario de contacto',
    service_webDev_feature4: 'Integración con redes sociales',
    service_webDev_feature5: 'Soporte post-entrega incluido',
    service_softwareDev_title: 'Software a la medida',
    service_softwareDev_desc: 'Aplicaciones web, paneles de administración, integraciones y automatización de procesos.',
    service_softwareDev_feature1: 'Panel de administración',
    service_softwareDev_feature2: 'Base de datos personalizada',
    service_softwareDev_feature3: 'APIs e integraciones externas',
    service_softwareDev_feature4: 'Autenticación de usuarios',
    service_softwareDev_feature5: 'Documentación técnica',
    service_ecommerce_title: 'Tiendas en línea',
    service_ecommerce_desc: 'E-commerce con carrito, pagos y gestión de inventario, como esta misma tienda.',
    service_ecommerce_feature1: 'Carrito de compras',
    service_ecommerce_feature2: 'Gestión de inventario',
    service_ecommerce_feature3: 'Pagos en línea',
    service_ecommerce_feature4: 'Panel de pedidos y clientes',
    service_ecommerce_feature5: 'Catálogo de productos',
    service_maintenance_title: 'Mantenimiento y soporte',
    service_maintenance_desc: 'Actualizaciones, correcciones, hosting y mejoras continuas de tus proyectos.',
    service_maintenance_feature1: 'Actualizaciones de contenido',
    service_maintenance_feature2: 'Corrección de errores',
    service_maintenance_feature3: 'Copias de seguridad regulares',
    service_maintenance_feature4: 'Monitoreo del sitio',
    service_maintenance_feature5: 'Soporte por WhatsApp',
    servicesHowItWorks: 'Cómo trabajamos',
    process_discover_title: 'Conversación inicial',
    process_discover_desc: 'Entendemos tu negocio, objetivos y presupuesto por WhatsApp o correo.',
    process_plan_title: 'Propuesta',
    process_plan_desc: 'Te enviamos alcance, tiempos y precio antes de empezar.',
    process_build_title: 'Desarrollo',
    process_build_desc: 'Construimos en etapas con revisiones para que veas el avance.',
    process_deliver_title: 'Entrega',
    process_deliver_desc: 'Lanzamos tu proyecto y te acompañamos con soporte post-entrega.',
    servicesPricingTitle: 'Precios de referencia',
    servicesPricingShowAll: 'Ver todos los precios',
    servicesPricingShowLess: 'Ver menos',
    servicesPricingRateNote: 'Tipo de cambio en vivo: $1 ≈ ₡{rate}',
    servicesPricingNote: 'Los precios son de referencia. El costo final depende de los requerimientos, diseño y funcionalidades específicas de tu proyecto.',
    servicePricing_colProject: 'Tipo de proyecto',
    servicePricing_colPrice: 'Precio de entrada',
    servicePricing_row1_name: 'Landing page estática (1 página)',
    servicePricing_row1_price: '₡50.000 – ₡80.000',
    servicePricing_row2_name: 'Sitio web básico (3-5 secciones)',
    servicePricing_row2_price: '₡80.000 – ₡150.000',
    servicePricing_row3_name: 'Portafolio profesional',
    servicePricing_row3_price: '₡100.000 – ₡180.000',
    servicePricing_row4_name: 'Página para artista (galería, contacto, obras)',
    servicePricing_row4_price: '₡120.000 – ₡250.000',
    servicePricing_row5_name: 'Catálogo de productos sin pagos',
    servicePricing_row5_price: '₡150.000 – ₡300.000',
    servicePricing_row6_name: 'Blog con CMS (WordPress, etc.)',
    servicePricing_row6_price: '₡150.000 – ₡350.000',
    servicePricing_row7_name: 'Tienda en línea básica',
    servicePricing_row7_price: '₡300.000 – ₡600.000',
    servicePricing_row8_name: 'Sistema de reservas (citas)',
    servicePricing_row8_price: '₡400.000 – ₡800.000',
    servicePricing_row9_name: 'Aplicación web CRUD (usuarios, login, panel)',
    servicePricing_row9_price: '₡500.000 – ₡1.000.000',
    servicePricing_row10_name: 'SaaS/MVP para startup',
    servicePricing_row10_price: '₡1.000.000 – ₡3.000.000',
    servicePricing_row11_name: 'App móvil sencilla (React Native/Flutter)',
    servicePricing_row11_price: '₡800.000 – ₡2.000.000',
    servicePricing_row12_name: 'Sistema empresarial a medida',
    servicePricing_row12_price: '₡2.000.000+',
    servicesAdditionalTitle: 'Servicios adicionales',
    servicesAdditional_colService: 'Servicio',
    servicesAdditional_colPrice: 'Precio',
    servicesAdditional_row1_name: 'Dominio (.com)',
    servicesAdditional_row1_price: 'Desde ₡5.000/año',
    servicesAdditional_row2_name: 'Hosting anual',
    servicesAdditional_row2_price: 'Desde ₡10.000/año',
    servicesAdditional_row3_name: 'Configuración inicial hosting',
    servicesAdditional_row3_price: '₡20.000 – ₡50.000',
    servicesAdditional_row4_name: 'SEO básico',
    servicesAdditional_row4_price: '₡30.000 – ₡100.000',
    servicesAdditional_row5_name: 'Google Analytics',
    servicesAdditional_row5_price: '₡15.000 – ₡50.000',
    servicesAdditional_row6_name: 'Mantenimiento mensual',
    servicesAdditional_row6_price: '₡15.000 – ₡100.000',
    servicesAdditional_row7_name: 'Cambios menores por hora',
    servicesAdditional_row7_price: '₡10.000 – ₡25.000/hora',
    servicesAdditional_row8_name: 'Diseño en Figma',
    servicesAdditional_row8_price: '₡50.000 – ₡300.000',
    servicesGetStarted: '¿Listo para empezar?',
    servicesGetStartedText: 'La mayoría de proyectos se cotizan según tus necesidades. Escríbenos por WhatsApp con una idea breve y te respondemos pronto.',
    servicesRequestQuote: 'Cotizar por WhatsApp',
    servicesViewPortfolio: 'Ver mi portafolio',
    servicesWhatsAppMessage: 'Hola, me interesa un servicio de desarrollo web o software. ¿Podemos hablar sobre mi proyecto?',
    servicesPromoTitle: '¿Necesitas una página web o software?',
    servicesPromoText: 'Diseñamos sitios, tiendas en línea y aplicaciones a la medida para tu negocio.',
    servicesPromoCta: 'Ver servicios',
    
    // Sorting
    sortBy: 'Ordenar por',
    priceAsc: 'Precio: Menor a Mayor',
    priceDesc: 'Precio: Mayor a Menor',
    nameAsc: 'Nombre: A-Z',
    nameDesc: 'Nombre: Z-A',
    newest: 'Más Recientes',
    oldest: 'Más Antiguos',
    
    // Condition
    condition: 'Condición',
    new: 'Nuevo',
    used: 'Usado',
    allConditions: 'Todas las Condiciones',
    
    // Product Detail
    loadingProduct: 'Cargando producto...',
    productNotFound: 'Producto no encontrado',
    backToProducts: '← Volver a Productos',
    quantity: 'Cantidad',
    addToCart: 'Agregar al Carrito',
    productAddedToCart: '¡Producto agregado al carrito!',
    errorAddingToCart: 'Error al agregar producto al carrito',
    stock: 'Stock',
    available: 'disponible',
    unavailable: 'no disponible',
    outOfStock: 'Agotado',
    productOutOfStock: 'Este producto está agotado',
    notEnoughStock: 'No hay suficiente stock disponible',
    
    // About
    aboutTitle: 'Acerca de IsaStore',
    ourStory: 'Nuestra Historia',
    ourMission: 'Nuestra Misión',
    ourMissionText: 'Creemos que la tecnología debe mejorar tu vida, no complicarla. Además de electrónicos y accesorios, diseñamos y desarrollamos páginas web y software a la medida para negocios que quieren crecer en línea.',
    aboutServicesText: 'También ofrecemos desarrollo de páginas web, tiendas en línea y software personalizado para empresas en Costa Rica y más allá.',
    whatWeOffer: 'Lo que Ofrecemos',
    whyChooseUs: '¿Por qué Elegirnos?',
    fastShipping: '🚚 Envío Rápido',
    fastShippingText: 'Entrega rápida y confiable a tu puerta',
    qualityGuarantee: '🛡️ Garantía de Calidad',
    qualityGuaranteeText: 'Todos los productos vienen con garantía',
    support247: '💬 Soporte 24/7',
    support247Text: 'Nuestro equipo está aquí para ayudarte en cualquier momento',
    bestPrices: '💰 Mejores Precios',
    bestPricesText: 'Precios competitivos sin comprometer la calidad',
    contactUs: 'Contáctanos',
    contactUsText: '¿Tienes preguntas o necesitas asistencia? ¡Estamos aquí para ayudarte! Comunícate con nosotros a través de nuestros canales de contacto o visita nuestra tienda para un servicio personalizado.',
    contactEmail: 'Email: isastoretech@gmail.com',
    contactPhone: 'Teléfono: +506 83047863',
    contactAddress: 'Dirección: Belén, Heredia, Costa Rica',
    storeAddress: 'Belén, Heredia, Costa Rica',
    storeEmail: 'isastoretech@gmail.com',
    storePhone: '+506 83047863',
    openInGoogleMaps: 'Google Maps',
    openInWaze: 'Abrir en Waze',
    
    // Footer
    footerDescription: 'Electrónicos, accesorios tecnológicos y desarrollo web y de software.',
    quickLinks: 'Enlaces Rápidos',
    support: 'Soporte',
    contactInfo: 'Información de Contacto',
    whatsappUs: 'Escríbenos por WhatsApp',
    whatsAppGreeting: 'Hola, me gustaría obtener más información sobre sus productos.',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    allRightsReserved: 'Todos los derechos reservados',
    developedBy: 'Desarrollado por',
    
    // Admin
    adminDashboard: 'Panel de Administración',
    welcomeAdmin: 'Bienvenido',
    changePassword: 'Cambiar Contraseña',
    addNewProduct: 'Agregar Nuevo Producto',
    editProduct: 'Editar Producto',
    cancel: 'Cancelar',
    hideFromMainPage: 'Ocultar de la página principal',
    saveProduct: 'Guardar Producto',
    edit: 'Editar',
    delete: 'Eliminar',
    productName: 'Nombre del Producto',
    price: 'Precio',
    description: 'Descripción',
    category: 'Categoría',
    selectCategory: 'Selecciona una categoría',
    images: 'Imágenes',
    enterImageFilename: 'O ingresa nombre del archivo de imagen',
    existingImages: 'Imágenes existentes:',
    weight: 'Peso (kg)',
    manageCategories: 'Gestionar Categorías',
    hideCategories: 'Ocultar Categorías',
    manageDiscounts: 'Gestionar Descuentos',
    hideDiscounts: 'Ocultar Descuentos',
    discountManager: 'Gestor de Descuentos',
    addDiscountTier: 'Agregar Nivel de Descuento',
    editDiscountTier: 'Editar Nivel de Descuento',
    minQuantity: 'Cantidad Mínima',
    discountPercent: 'Porcentaje de Descuento',
    active: 'Activo',
    inactive: 'Inactivo',
    status: 'Estado',
    actions: 'Acciones',
    create: 'Crear',
    update: 'Actualizar',
    items: 'artículos',
    noDiscountTiers: 'No hay niveles de descuento configurados',
    confirmDeleteDiscountTier: '¿Estás seguro de que deseas eliminar el descuento de {percent}% para {quantity}+ artículos?',
    loadingDiscounts: 'Cargando descuentos...',
    
    // Breadcrumb
    details: 'Detalles',
    product: 'Producto',
    products: 'Productos',
    noProducts: 'No hay productos',
    
    // Orders
    myOrders: 'Mis Pedidos',
    loadingOrders: 'Cargando pedidos...',
    noOrdersYet: 'Aún no hay ningún pedido',
    order: 'Pedido',
    
    // Checkout Form
    checkoutInformation: 'Información de Compra',
    fullName: 'Nombre Completo',
    email: 'Correo Electrónico',
    phone: 'Teléfono',
    address: 'Dirección',
    city: 'Ciudad',
    zipCode: 'Código Postal',
    fieldRequired: 'Este campo es obligatorio',
    invalidEmail: 'Correo electrónico inválido',
    invalidPhone: 'El teléfono debe tener exactamente 8 dígitos',
    phoneWithDigits: 'Teléfono * (8 dígitos)',
    phone8Digits: '8 dígitos',
    completePurchase: 'Completar Compra',
    
    // Cart Messages
    orderPlacedSuccess: '¡Pedido realizado con éxito!',
    errorPlacingOrder: 'Error al realizar el pedido',
    
    // WhatsApp Checkout
    completeViaWhatsApp: 'Completar por WhatsApp',
    whatsAppPhone: '50683047863',
    whatsAppMessagePrefix: 'Hola! Me gustaría realizar el siguiente pedido:',
    
    // Contact Page
    contactTitle: 'Contáctanos',
    contactDescription: 'Estamos aquí para ayudarte. Si tienes alguna pregunta, comentario o necesitas asistencia, no dudes en contactarnos a través de cualquiera de nuestros canales.',
    whatsapp: 'WhatsApp',
    
    // Shipping Page
    shippingTitle: 'Información de Envío',
    shippingMethods: 'Métodos de Envío',
    shippingMethodsDescription: 'Realizamos envíos a cualquier parte del país utilizando los siguientes métodos:',
    shippingMethod1: '📮 Correos de Costa Rica - Envíos a todo el país (2 a 4 días hábiles)',
    shippingMethod2: '🚗 Uber Flash - Cotización disponible dentro del GAM (Gran Área Metropolitana) - Mismo día',
    pickupOption: '📍 Recogida en tienda - Belén (Puedes pagar al momento de recoger)',
    pickupTitle: 'Recogida en Tienda',
    pickupDescription: 'También puedes venir a recoger tu pedido directamente en nuestra ubicación en Belén. Si eliges esta opción, puedes pagar al momento de la recogida.',
    paymentMethods: 'Métodos de Pago',
    paymentMethodsDescription: 'Aceptamos los siguientes métodos de pago:',
    paymentMethod1: '💳 SINPE',
    paymentMethod2: '🏦 Transferencia bancaria',
    paymentMethod3: '💵 Efectivo',
    paymentNote: '⚠️ IMPORTANTE: Para envíos por correo o Uber Flash, el pago debe completarse antes del envío. Si recoges en tienda, puedes pagar al momento de la recogida.',
    warranty: 'Garantía',
    warrantyDescription: 'Todos nuestros productos vienen con garantía según el tipo de artículo:',
    warrantyUsed: '📦 Artículos usados: 1 mes de garantía',
    warrantyNew: '✨ Artículos nuevos: 3 meses de garantía',
    shippingInfo: 'Información de Envío',
    shippingMethod: 'Método de Envío',
    shippingPickup: 'Recogida en Tienda (Belén)',
    shippingCorreos: 'Correos de Costa Rica',
    shippingUber: 'Uber Flash',
    requestPriceWhatsApp: 'Solicitar precio por WhatsApp',
    shippingCorreosInfo: 'Peso total: {weight} kg - Costo: ₡{cost}',
    shippingUberInfo: 'El precio de envío se cotizará y confirmará por WhatsApp',
    freeShippingConditions: '💡 Envío puede ser GRATIS en GAM para pedidos sobre ₡75,000. Condiciones aplican.',
    
    // Returns Page
    returnsTitle: 'Política de Devoluciones',
    returns: 'Devoluciones',
    returnPolicy: 'Política de Devoluciones',
    returnPolicyDescription: 'Queremos que estés completamente satisfecho con tu compra. Si no estás contento con tu producto, puedes devolverlo siguiendo nuestra política de devoluciones.',
    returnPeriod: 'Período de Devolución',
    returnPeriodDescription: '⚠️ Las devoluciones se aceptan en un plazo máximo de 48 horas después de la compra.',
    returnConditions: 'Condiciones para Devolución',
    returnCondition1: 'El producto debe estar en su empaque original sin abrir',
    returnCondition2: 'Debe incluir todos los accesorios y documentación original',
    returnCondition3: 'El producto no debe tener signos de uso o daño',
    returnCondition4: 'Debe presentarse el comprobante de compra',
    howToReturn: 'Cómo Devolver un Producto',
    returnStep1: 'Contáctanos por WhatsApp o email dentro del período de devolución',
    returnStep2: 'Describe el motivo de la devolución',
    returnStep3: 'Nuestro equipo te proporcionará las instrucciones de devolución',
    returnStep4: 'Una vez recibido y verificado, procesaremos el reembolso',
    refundProcess: 'Proceso de Reembolso',
    refundProcessDescription: 'El reembolso se realiza inmediatamente al recibir y revisar el artículo devuelto. El reembolso se realizará mediante el mismo método de pago utilizado.',
    
    // FAQ Page
    faqTitle: 'Preguntas Frecuentes',
    faq: 'Preguntas Frecuentes',
    faqDescription: 'Encuentra respuestas a las preguntas más comunes sobre nuestros productos, envíos, devoluciones y más.',
    faq1Question: '¿Cómo puedo realizar un pedido?',
    faq1Answer: 'Puedes realizar un pedido agregando productos al carrito desde nuestra página web y completando el proceso de compra a través de WhatsApp. Solo necesitas proporcionar tu nombre completo, teléfono (8 dígitos) y dirección. Una vez que confirmes tu pedido por WhatsApp, procederemos con el envío.',
    faq2Question: '¿Cuáles son los métodos de pago aceptados?',
    faq2Answer: 'Aceptamos los siguientes métodos de pago: SINPE, transferencia bancaria y efectivo. Es importante mencionar que NO se envían productos que no se hayan pagado. El pago debe completarse antes del envío.',
    faq3Question: '¿Cuáles son las opciones de envío disponibles?',
    faq3Answer: 'Ofrecemos tres opciones: 1) Envíos por Correos de Costa Rica a cualquier parte del país, 2) Uber Flash para cotización dentro del GAM (Gran Área Metropolitana), y 3) Puedes venir a recoger tu pedido directamente en nuestra ubicación en Belén.',
    faq4Question: '¿Cuánto tiempo tengo para devolver un producto?',
    faq4Answer: 'Las devoluciones se aceptan en un plazo máximo de 48 horas después de la compra. El producto debe estar en su empaque original sin abrir, incluir todos los accesorios y documentación, y no debe tener signos de uso o daño.',
    faq5Question: '¿Qué garantía ofrecen los productos?',
    faq5Answer: 'Todos nuestros productos vienen con garantía según el tipo de artículo: Artículos usados tienen 1 mes de garantía y artículos nuevos tienen 3 meses de garantía.',
    faq6Question: '¿Puedo pagar al momento de recibir el pedido?',
    faq6Answer: 'Para envíos por correo o Uber Flash, el pago debe completarse antes del envío. Sin embargo, si vienes a recoger tu pedido en nuestra tienda en Belén, puedes pagar al momento de la recogida.',
    
    // Privacy Page
    privacyTitle: 'Política de Privacidad',
    lastUpdated: 'Última actualización',
    privacyIntroduction: 'Introducción',
    privacyIntroductionText: 'En IsaStore, nos comprometemos a proteger tu privacidad y tus datos personales. Esta política explica cómo recopilamos, usamos y protegemos tu información.',
    informationWeCollect: 'Información que Recopilamos',
    informationWeCollectDescription: 'Recopilamos la siguiente información cuando realizas una compra:',
    infoCollected1: 'Nombre completo',
    infoCollected2: 'Número de teléfono',
    infoCollected3: 'Dirección de entrega',
    infoCollected4: 'Información de pedidos (historial de compras)',
    howWeUseInfo: 'Cómo Usamos tu Información',
    howWeUseInfoDescription: 'Utilizamos tu información para:',
    useInfo1: 'Procesar y completar tus pedidos',
    useInfo2: 'Comunicarnos contigo sobre tu pedido',
    useInfo3: 'Proporcionar servicio al cliente y soporte',
    useInfo4: 'Mejorar nuestros productos y servicios',
    dataProtection: 'Protección de Datos',
    dataProtectionDescription: 'Implementamos medidas de seguridad técnicas y organizativas para proteger tu información personal. Tu información de contacto se utiliza para coordinar la entrega de pedidos vía WhatsApp. No compartimos tus datos con otros terceros sin tu consentimiento, excepto cuando sea necesario para cumplir con la ley.',
    dataRetention: 'Retención de Datos',
    dataRetentionDescription: 'Conservamos tu información personal únicamente mientras sea necesaria para gestionar tu pedido y cumplir con obligaciones legales. Los datos de contacto asociados a pedidos se conservan por un máximo de 2 años.',
    yourRights: 'Tus Derechos',
    yourRightsDescription: 'Tienes derecho a:',
    right1: 'Acceder a los datos personales que tenemos sobre ti',
    right2: 'Solicitar la corrección de datos inexactos',
    right3: 'Solicitar la eliminación de tus datos personales',
    right4: 'Contactarnos en cualquier momento para ejercer estos derechos',
    cookiesTitle: 'Cookies y Almacenamiento Local',
    cookiesDescription: 'Este sitio utiliza almacenamiento local del navegador (localStorage) únicamente para el funcionamiento esencial del servicio. No utilizamos cookies de rastreo, publicidad ni análisis de terceros.',
    cookiesTableStorage: 'Tipo',
    cookiesTablePurpose: 'Propósito',
    cookiesTableRetention: 'Retención',
    cookieRow1Storage: 'Carrito de compras',
    cookieRow1Purpose: 'Guarda los artículos en tu carrito entre visitas',
    cookieRow1Retention: 'Hasta que vacíes el carrito o borres los datos del navegador',
    cookieRow2Storage: 'Caché del catálogo',
    cookieRow2Purpose: 'Almacena temporalmente productos y categorías para cargas más rápidas',
    cookieRow2Retention: '5 minutos',
    cookiesRights: 'Puedes borrar estos datos en cualquier momento desde la configuración de tu navegador (Configuración → Privacidad → Borrar datos del sitio). Ten en cuenta que al hacerlo se vaciará tu carrito.',
    contactPrivacy: 'Contáctanos sobre Privacidad',
    contactPrivacyText: 'Si tienes preguntas sobre nuestra política de privacidad o sobre tus datos personales, contáctanos en:',
    
    // Terms Page
    termsTitle: 'Términos de Servicio',
    termsAcceptance: 'Aceptación de los Términos',
    termsAcceptanceText: 'Al utilizar nuestro sitio web y realizar una compra, aceptas estos términos de servicio. Si no estás de acuerdo, por favor no utilices nuestro servicio.',
    useOfService: 'Uso del Servicio',
    useOfServiceDescription: 'Al usar nuestro servicio, aceptas:',
    useService1: 'Proporcionar información precisa y actualizada',
    useService2: 'Usar el servicio solo para fines legales',
    useService3: 'No intentar acceder no autorizado a nuestros sistemas',
    useService4: 'Respetar los derechos de propiedad intelectual',
    ordersAndPayment: 'Pedidos y Pagos',
    ordersAndPaymentDescription: 'Todos los pedidos están sujetos a disponibilidad de stock. El precio mostrado al momento de realizar el pedido es el precio final garantizado. Aceptamos los siguientes métodos de pago: SINPE, transferencia bancaria y efectivo. Para envíos, el pago debe completarse antes del despacho.',
    productAvailability: 'Disponibilidad de Productos',
    productAvailabilityDescription: 'Hacemos nuestro mejor esfuerzo para mantener nuestro inventario actualizado. Si un producto no está disponible después de realizar tu pedido, te contactaremos para ofrecerte alternativas o reembolsar tu pago.',
    shippingReturnsTerms: 'Envíos y Devoluciones',
    shippingReturnsTermsDescription: 'Las condiciones detalladas de envío y devoluciones se encuentran en nuestras páginas de Política de Envío y Política de Devoluciones.',
    limitationOfLiability: 'Limitación de Responsabilidad',
    limitationOfLiabilityDescription: 'IsaStore no será responsable por daños indirectos, incidentales o consecuentes que surjan del uso de nuestros productos o servicios, más allá del valor del producto comprado.',
    governingLaw: 'Ley Aplicable',
    governingLawDescription: 'Estos términos de servicio se rigen por las leyes de la República de Costa Rica. Cualquier disputa será resuelta conforme a la legislación costarricense vigente.',
    contactTerms: 'Contáctanos sobre los Términos',
    contactTermsText: 'Si tienes preguntas sobre estos términos de servicio, contáctanos en:',

    // Admin - Password
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmNewPassword: 'Confirmar Nueva Contraseña',
    passwordChangedSuccess: 'Contraseña cambiada exitosamente',
    errorChangingPassword: 'Error al cambiar la contraseña',
    confirmDeleteProduct: '¿Estás seguro de que deseas eliminar este producto?',
    productCreated: 'Producto creado exitosamente',
    productUpdated: 'Producto actualizado exitosamente',
    productDeleted: 'Producto eliminado exitosamente',
    errorSavingProduct: 'Error al guardar el producto',
    errorDeletingProduct: 'Error al eliminar el producto',

    // Category Manager
    categoryManagement: 'Gestión de Categorías',
    addCategory: 'Agregar Categoría',
    editCategory: 'Editar Categoría',
    addNewCategory: 'Agregar Nueva Categoría',
    categoryIdPlaceholder: 'ID de Categoría (ej., Laptops)',
    englishName: 'Nombre en Inglés',
    spanishName: 'Nombre en Español',
    categoryId: 'ID de Categoría',
    errorSavingCategory: 'Error al guardar categoría',
    cannotDeleteCategory: 'No se puede eliminar "{name}" porque tiene {count} producto(s). Reasigna o elimina los productos primero.',
    confirmDeleteCategory: '¿Estás seguro de que deseas eliminar "{name}"?',
    errorDeletingCategory: 'Error al eliminar categoría',

    // Discount Manager - errors
    errorSavingDiscount: 'Error al guardar nivel de descuento',
    errorDeletingDiscount: 'Error al eliminar nivel de descuento',

    // Confirm clear cart
    confirmClearCart: '¿Estás seguro de que deseas vaciar el carrito?',

    // Error Boundary
    errorBoundaryTitle: 'Algo salió mal',
    errorBoundaryMessage: 'Ocurrió un error inesperado. Por favor recarga la página.',
    errorBoundaryReload: 'Recargar Página',

    // Free server banner
    freeServerBanner: 'Despertando al servidor. Los productos pueden tardar ~10 segundos en cargar. Si no cargan, recarga la página manualmente.',
    freeServerError: 'No se pudo conectar con el servidor. Este sitio usa un servidor que puede estar inactivo. Por favor, recarga la página en unos segundos.',
  },
  en: {
    // Navigation
    home: 'Home',
    about: 'About',
    services: 'Services',
    cart: 'Cart',
    orders: 'Orders',
    adminPanel: 'Admin Dashboard',
    logout: 'Logout',
    adminLogin: 'Login',
    
    // Product List
    ourProducts: 'Our Products',
    loadingProducts: 'Loading products...',
    viewDetails: 'View',
    
    // Cart
    shoppingCart: 'Shopping Cart',
    loadingCart: 'Loading cart...',
    emptyCart: 'Your cart is empty',
    continueShopping: 'Continue Shopping',
    remove: 'Remove',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    calculatedAtCheckout: 'Calculated at checkout',
    bulkDiscount: 'Bulk Discount',
    bulkDiscountApplied: '🎉 {percent}% discount applied for buying {quantity}+ items!',
    buyXAndSave: 'Buy {quantity}+ and save {percent}%',
    savePercent: 'Save {percent}%',
    discountAppliedForQuantity: '{percent}% discount applied for buying {quantity} items',
    total: 'Total',
    checkout: 'Checkout',
    clearCart: 'Clear Cart',
    
    // Categories
    allProducts: 'All Products',
    more: 'more',
    showLess: 'Show less',
    chargers: 'Chargers',
    laptops: 'Laptops',
    ipads: 'iPads',
    accessories: 'Accessories',
    other: 'Other',
    noCategories: 'No categories available',

    // Services page
    servicesTitle: 'Web & Software Development',
    servicesSubtitle: 'We build websites, online stores, and custom applications. Tell us about your project and we will send you a quote with no obligation.',
    servicesWhatWeBuild: 'What we build',
    service_webDev_title: 'Websites',
    service_webDev_desc: 'Corporate sites, portfolios, and landing pages optimized for mobile and SEO.',
    service_webDev_feature1: 'Responsive design (mobile & desktop)',
    service_webDev_feature2: 'Basic SEO optimization',
    service_webDev_feature3: 'Contact form',
    service_webDev_feature4: 'Social media integration',
    service_webDev_feature5: 'Post-delivery support included',
    service_softwareDev_title: 'Custom software',
    service_softwareDev_desc: 'Web apps, admin dashboards, integrations, and process automation.',
    service_softwareDev_feature1: 'Admin dashboard',
    service_softwareDev_feature2: 'Custom database',
    service_softwareDev_feature3: 'APIs & external integrations',
    service_softwareDev_feature4: 'User authentication',
    service_softwareDev_feature5: 'Technical documentation',
    service_ecommerce_title: 'Online stores',
    service_ecommerce_desc: 'E-commerce with cart, checkout, and inventory management — like this store.',
    service_ecommerce_feature1: 'Shopping cart',
    service_ecommerce_feature2: 'Inventory management',
    service_ecommerce_feature3: 'Online payments',
    service_ecommerce_feature4: 'Orders & customers panel',
    service_ecommerce_feature5: 'Product catalog',
    service_maintenance_title: 'Maintenance & support',
    service_maintenance_desc: 'Updates, bug fixes, hosting, and ongoing improvements for your projects.',
    service_maintenance_feature1: 'Content updates',
    service_maintenance_feature2: 'Bug fixes',
    service_maintenance_feature3: 'Regular backups',
    service_maintenance_feature4: 'Site monitoring',
    service_maintenance_feature5: 'WhatsApp support',
    servicesHowItWorks: 'How we work',
    process_discover_title: 'Initial conversation',
    process_discover_desc: 'We learn about your business, goals, and budget via WhatsApp or email.',
    process_plan_title: 'Proposal',
    process_plan_desc: 'You receive scope, timeline, and pricing before we start.',
    process_build_title: 'Development',
    process_build_desc: 'We build in stages with reviews so you can see progress.',
    process_deliver_title: 'Launch',
    process_deliver_desc: 'We deploy your project and provide post-launch support.',
    servicesPricingTitle: 'Reference prices',
    servicesPricingShowAll: 'See all prices',
    servicesPricingShowLess: 'Show less',
    servicesPricingRateNote: 'Live exchange rate: $1 ≈ ₡{rate}',
    servicesPricingNote: 'Prices are for reference. The final cost depends on the specific requirements, design, and features of your project.',
    servicePricing_colProject: 'Project type',
    servicePricing_colPrice: 'Starting price',
    servicePricing_row1_name: 'Static landing page (1 page)',
    servicePricing_row1_price: '₡50,000 – ₡80,000',
    servicePricing_row2_name: 'Basic website (3-5 sections)',
    servicePricing_row2_price: '₡80,000 – ₡150,000',
    servicePricing_row3_name: 'Professional portfolio',
    servicePricing_row3_price: '₡100,000 – ₡180,000',
    servicePricing_row4_name: 'Artist page (gallery, contact, works)',
    servicePricing_row4_price: '₡120,000 – ₡250,000',
    servicePricing_row5_name: 'Product catalog (no payments)',
    servicePricing_row5_price: '₡150,000 – ₡300,000',
    servicePricing_row6_name: 'Blog with CMS (WordPress, etc.)',
    servicePricing_row6_price: '₡150,000 – ₡350,000',
    servicePricing_row7_name: 'Basic online store',
    servicePricing_row7_price: '₡300,000 – ₡600,000',
    servicePricing_row8_name: 'Booking/appointment system',
    servicePricing_row8_price: '₡400,000 – ₡800,000',
    servicePricing_row9_name: 'CRUD web app (users, login, panel)',
    servicePricing_row9_price: '₡500,000 – ₡1,000,000',
    servicePricing_row10_name: 'SaaS/MVP for startup',
    servicePricing_row10_price: '₡1,000,000 – ₡3,000,000',
    servicePricing_row11_name: 'Simple mobile app (React Native/Flutter)',
    servicePricing_row11_price: '₡800,000 – ₡2,000,000',
    servicePricing_row12_name: 'Custom enterprise system',
    servicePricing_row12_price: '₡2,000,000+',
    servicesAdditionalTitle: 'Additional services',
    servicesAdditional_colService: 'Service',
    servicesAdditional_colPrice: 'Price',
    servicesAdditional_row1_name: 'Domain (.com)',
    servicesAdditional_row1_price: 'From ₡5,000/yr',
    servicesAdditional_row2_name: 'Annual hosting',
    servicesAdditional_row2_price: 'From ₡10,000/yr',
    servicesAdditional_row3_name: 'Initial hosting setup',
    servicesAdditional_row3_price: '₡20,000 – ₡50,000',
    servicesAdditional_row4_name: 'Basic SEO',
    servicesAdditional_row4_price: '₡30,000 – ₡100,000',
    servicesAdditional_row5_name: 'Google Analytics',
    servicesAdditional_row5_price: '₡15,000 – ₡50,000',
    servicesAdditional_row6_name: 'Monthly maintenance',
    servicesAdditional_row6_price: '₡15,000 – ₡100,000',
    servicesAdditional_row7_name: 'Minor changes per hour',
    servicesAdditional_row7_price: '₡10,000 – ₡25,000/hr',
    servicesAdditional_row8_name: 'Figma design',
    servicesAdditional_row8_price: '₡50,000 – ₡300,000',
    servicesGetStarted: 'Ready to get started?',
    servicesGetStartedText: 'Most projects are quoted based on your needs. Message us on WhatsApp with a short description and we will get back to you soon.',
    servicesRequestQuote: 'Get a quote on WhatsApp',
    servicesViewPortfolio: 'View my portfolio',
    servicesWhatsAppMessage: 'Hello, I am interested in web or software development services. Can we discuss my project?',
    servicesPromoTitle: 'Need a website or custom software?',
    servicesPromoText: 'We build websites, online stores, and tailored apps for your business.',
    servicesPromoCta: 'View services',
    
    // Sorting
    sortBy: 'Sort by',
    priceAsc: 'Price: Low to High',
    priceDesc: 'Price: High to Low',
    nameAsc: 'Name: A-Z',
    nameDesc: 'Name: Z-A',
    newest: 'Newest First',
    oldest: 'Oldest First',
    
    // Condition
    condition: 'Condition',
    new: 'New',
    used: 'Used',
    allConditions: 'All Conditions',
    
    // Product Detail
    loadingProduct: 'Loading product...',
    productNotFound: 'Product not found',
    backToProducts: '← Back to Products',
    quantity: 'Quantity',
    addToCart: 'Add to Cart',
    productAddedToCart: 'Product added to cart!',
    errorAddingToCart: 'Error adding product to cart',
    unavailable: 'unavailable',
    outOfStock: 'Out of Stock',
    productOutOfStock: 'This product is out of stock',
    notEnoughStock: 'Not enough stock available',
    available: 'available',
    
    // About
    aboutTitle: 'About IsaStore',
    ourStory: 'Our Story',
    ourMission: 'Our Mission',
    ourMissionText: 'We believe technology should enhance your life, not complicate it. Beyond electronics and accessories, we design and build custom websites and software for businesses that want to grow online.',
    aboutServicesText: 'We also offer website development, online stores, and custom software for businesses in Costa Rica and beyond.',
    whatWeOffer: 'What We Offer',
    whyChooseUs: 'Why Choose Us?',
    fastShipping: '🚚 Fast Shipping',
    fastShippingText: 'Quick and reliable delivery to your door',
    qualityGuarantee: '🛡️ Quality Guarantee',
    qualityGuaranteeText: 'All products come with warranty',
    support247: '💬 24/7 Support',
    support247Text: 'Our team is here to help you anytime',
    bestPrices: '💰 Best Prices',
    bestPricesText: 'Competitive prices without compromising quality',
    contactUs: 'Contact Us',
    contactUsText: 'Have questions or need assistance? We\'re here to help! Reach out through our contact channels or visit our store for personalized service.',
    contactEmail: '📧 Email: isastoretech@gmail.com',
    contactPhone: '📞 Phone: +506 83047863',
    contactAddress: 'Address: Belén, Heredia, Costa Rica',
    storeAddress: 'Belén, Heredia, Costa Rica',
    storeEmail: 'isastoretech@gmail.com',
    storePhone: '+506 83047863',
    openInGoogleMaps: 'Google Maps',
    openInWaze: 'Open in Waze',
    
    // Footer
    footerDescription: 'Electronics, tech accessories, and custom web & software development.',
    quickLinks: 'Quick Links',
    support: 'Support',
    contactInfo: 'Contact Info',
    whatsappUs: 'WhatsApp Us',
    whatsAppGreeting: 'Hello, I would like to get more information about your products.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    allRightsReserved: 'All rights reserved',
    developedBy: 'Developed by',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    welcomeAdmin: 'Welcome',
    changePassword: 'Change Password',
    addNewProduct: 'Add New Product',
    editProduct: 'Edit Product',
    cancel: 'Cancel',
    hideFromMainPage: 'Hide from main page',
    saveProduct: 'Save Product',
    edit: 'Edit',
    delete: 'Delete',
    productName: 'Product Name',
    price: 'Price',
    description: 'Description',
    category: 'Category',
    selectCategory: 'Select a category',
    images: 'Images',
    enterImageFilename: 'Or enter image filename',
    existingImages: 'Existing images:',
    weight: 'Weight (kg)',
    manageCategories: 'Manage Categories',
    hideCategories: 'Hide Categories',
    manageDiscounts: 'Manage Discounts',
    hideDiscounts: 'Hide Discounts',
    discountManager: 'Discount Manager',
    addDiscountTier: 'Add Discount Tier',
    editDiscountTier: 'Edit Discount Tier',
    minQuantity: 'Minimum Quantity',
    discountPercent: 'Discount Percent',
    active: 'Active',
    inactive: 'Inactive',
    status: 'Status',
    actions: 'Actions',
    create: 'Create',
    update: 'Update',
    items: 'items',
    noDiscountTiers: 'No discount tiers configured',
    confirmDeleteDiscountTier: 'Are you sure you want to delete the {percent}% discount for {quantity}+ items?',
    loadingDiscounts: 'Loading discounts...',
    
    // Breadcrumb
    details: 'Details',
    product: 'Product',
    products: 'Products',
    noProducts: 'No products',
    
    // Orders
    myOrders: 'My Orders',
    loadingOrders: 'Loading orders...',
    noOrdersYet: 'You haven\'t placed any orders yet',
    order: 'Order',
    
    // Checkout Form
    checkoutInformation: 'Checkout Information',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    zipCode: 'Zip Code',
    fieldRequired: 'This field is required',
    invalidEmail: 'Invalid email address',
    invalidPhone: 'Phone must have exactly 8 digits',
    phoneWithDigits: 'Phone * (8 digits)',
    phone8Digits: '8 digits',
    completePurchase: 'Complete Purchase',
    
    // Cart Messages
    orderPlacedSuccess: 'Order placed successfully!',
    errorPlacingOrder: 'Error placing order',
    
    // WhatsApp Checkout
    completeViaWhatsApp: 'Complete via WhatsApp',
    whatsAppPhone: '50683047863',
    whatsAppMessagePrefix: 'Hello! I would like to place the following order:',
    
    // Contact Page
    contactTitle: 'Contact Us',
    contactDescription: 'We are here to help you. If you have any questions, comments, or need assistance, don\'t hesitate to contact us through any of our channels.',
    whatsapp: 'WhatsApp',
    
    // Shipping Page
    shippingTitle: 'Shipping Information',
    shippingMethods: 'Shipping Methods',
    shippingMethodsDescription: 'We ship to anywhere in the country using the following methods:',
    shippingMethod1: '📮 Correos de Costa Rica - Shipping nationwide (2 to 4 business days)',
    shippingMethod2: '🚗 Uber Flash - Quote available within GAM (Greater Metropolitan Area) - Same day',
    pickupOption: '📍 Store Pickup - Belén (You can pay at pickup)',
    pickupTitle: 'Store Pickup',
    pickupDescription: 'You can also come pick up your order directly at our location in Belén. If you choose this option, you can pay at the time of pickup.',
    paymentMethods: 'Payment Methods',
    paymentMethodsDescription: 'We accept the following payment methods:',
    paymentMethod1: '💳 SINPE',
    paymentMethod2: '🏦 Bank transfer',
    paymentMethod3: '💵 Cash',
    paymentNote: '⚠️ IMPORTANT: For shipments via mail or Uber Flash, payment must be completed before shipping. If you pick up in store, you can pay at the time of pickup.',
    warranty: 'Warranty',
    warrantyDescription: 'All our products come with warranty according to the type of item:',
    warrantyUsed: '📦 Used items: 1 month warranty',
    warrantyNew: '✨ New items: 3 months warranty',
    shippingInfo: 'Shipping Information',
    shippingMethod: 'Shipping Method',
    shippingPickup: 'Store Pickup (Belén)',
    shippingCorreos: 'Correos de Costa Rica',
    shippingUber: 'Uber Flash',
    requestPriceWhatsApp: 'Request price via WhatsApp',
    shippingCorreosInfo: 'Total weight: {weight} kg - Cost: ₡{cost}',
    shippingUberInfo: 'Shipping price will be quoted and confirmed via WhatsApp',
    freeShippingConditions: '💡 Delivery may be FREE in GAM for orders over ₡75,000. Conditions apply.',
    
    // Returns Page
    returnsTitle: 'Returns Policy',
    returns: 'Returns',
    returnPolicy: 'Returns Policy',
    returnPolicyDescription: 'We want you to be completely satisfied with your purchase. If you are not happy with your product, you can return it following our returns policy.',
    returnPeriod: 'Return Period',
    returnPeriodDescription: '⚠️ Returns are accepted within a maximum period of 48 hours after purchase.',
    returnConditions: 'Return Conditions',
    returnCondition1: 'The product must be in its original unopened packaging',
    returnCondition2: 'Must include all original accessories and documentation',
    returnCondition3: 'The product must not show signs of use or damage',
    returnCondition4: 'Must present proof of purchase',
    howToReturn: 'How to Return a Product',
    returnStep1: 'Contact us via WhatsApp or email within the return period',
    returnStep2: 'Describe the reason for the return',
    returnStep3: 'Our team will provide you with return instructions',
    returnStep4: 'Once received and verified, we will process the refund',
    refundProcess: 'Refund Process',
    refundProcessDescription: 'The refund is processed immediately upon receiving and reviewing the returned item. The refund will be made using the same payment method used.',
    
    // FAQ Page
    faqTitle: 'Frequently Asked Questions',
    faq: 'FAQ',
    faqDescription: 'Find answers to the most common questions about our products, shipping, returns and more.',
    faq1Question: 'How can I place an order?',
    faq1Answer: 'You can place an order by adding products to your cart from our website and completing the checkout process through WhatsApp. You just need to provide your full name, phone number (8 digits), and address. Once you confirm your order via WhatsApp, we will proceed with shipping.',
    faq2Question: 'What payment methods are accepted?',
    faq2Answer: 'We accept the following payment methods: SINPE, bank transfer, and cash. It is important to note that products are NOT shipped until paid. Payment must be completed before shipping.',
    faq3Question: 'What shipping options are available?',
    faq3Answer: 'We offer three options: 1) Shipping via Correos de Costa Rica anywhere in the country, 2) Uber Flash for quotes within GAM (Greater Metropolitan Area), and 3) You can pick up your order directly at our location in Belén.',
    faq4Question: 'How long do I have to return a product?',
    faq4Answer: 'Returns are accepted within a maximum period of 48 hours after purchase. The product must be in its original unopened packaging, include all accessories and documentation, and must not show signs of use or damage.',
    faq5Question: 'What warranty do you offer on products?',
    faq5Answer: 'All our products come with warranty according to the type of item: Used items have 1 month warranty and new items have 3 months warranty.',
    faq6Question: 'Can I pay when I receive the order?',
    faq6Answer: 'For shipments via mail or Uber Flash, payment must be completed before shipping. However, if you come to pick up your order at our store in Belén, you can pay at the time of pickup.',
    
    // Privacy Page
    privacyTitle: 'Privacy Policy',
    lastUpdated: 'Last updated',
    privacyIntroduction: 'Introduction',
    privacyIntroductionText: 'At IsaStore, we are committed to protecting your privacy and personal data. This policy explains how we collect, use, and protect your information.',
    informationWeCollect: 'Information We Collect',
    informationWeCollectDescription: 'We collect the following information when you make a purchase:',
    infoCollected1: 'Full name',
    infoCollected2: 'Phone number',
    infoCollected3: 'Delivery address',
    infoCollected4: 'Order information (purchase history)',
    howWeUseInfo: 'How We Use Your Information',
    howWeUseInfoDescription: 'We use your information to:',
    useInfo1: 'Process and complete your orders',
    useInfo2: 'Communicate with you about your order',
    useInfo3: 'Provide customer service and support',
    useInfo4: 'Improve our products and services',
    dataProtection: 'Data Protection',
    dataProtectionDescription: 'We implement technical and organizational security measures to protect your personal information. Your contact information is used to coordinate order delivery via WhatsApp. We do not share your data with other third parties without your consent, except when necessary to comply with the law.',
    dataRetention: 'Data Retention',
    dataRetentionDescription: 'We retain your personal information only for as long as necessary to manage your order and comply with legal obligations. Contact data associated with orders is kept for a maximum of 2 years.',
    yourRights: 'Your Rights',
    yourRightsDescription: 'You have the right to:',
    right1: 'Access the personal data we hold about you',
    right2: 'Request correction of inaccurate data',
    right3: 'Request deletion of your personal data',
    right4: 'Contact us at any time to exercise these rights',
    cookiesTitle: 'Cookies and Local Storage',
    cookiesDescription: 'This site uses browser local storage (localStorage) only for essential service functionality. We do not use tracking, advertising, or third-party analytics cookies.',
    cookiesTableStorage: 'Type',
    cookiesTablePurpose: 'Purpose',
    cookiesTableRetention: 'Retention',
    cookieRow1Storage: 'Shopping cart',
    cookieRow1Purpose: 'Saves your cart items between visits',
    cookieRow1Retention: 'Until you clear your cart or browser data',
    cookieRow2Storage: 'Catalog cache',
    cookieRow2Purpose: 'Temporarily stores products and categories for faster page loads',
    cookieRow2Retention: '5 minutes',
    cookiesRights: 'You can delete this data at any time from your browser settings (Settings → Privacy → Clear site data). Note that doing so will empty your shopping cart.',
    contactPrivacy: 'Contact Us About Privacy',
    contactPrivacyText: 'If you have questions about our privacy policy or your personal data, contact us at:',
    
    // Terms Page
    termsTitle: 'Terms of Service',
    termsAcceptance: 'Acceptance of Terms',
    termsAcceptanceText: 'By using our website and making a purchase, you accept these terms of service. If you do not agree, please do not use our service.',
    useOfService: 'Use of Service',
    useOfServiceDescription: 'By using our service, you agree to:',
    useService1: 'Provide accurate and up-to-date information',
    useService2: 'Use the service only for legal purposes',
    useService3: 'Not attempt unauthorized access to our systems',
    useService4: 'Respect intellectual property rights',
    ordersAndPayment: 'Orders and Payment',
    ordersAndPaymentDescription: 'All orders are subject to stock availability. The price shown at the time of placing your order is the guaranteed final price. We accept the following payment methods: SINPE, bank transfer, and cash. For shipments, payment must be completed before dispatch.',
    productAvailability: 'Product Availability',
    productAvailabilityDescription: 'We do our best to keep our inventory updated. If a product is not available after placing your order, we will contact you to offer alternatives or refund your payment.',
    shippingReturnsTerms: 'Shipping and Returns',
    shippingReturnsTermsDescription: 'Detailed shipping and returns conditions can be found on our Shipping Policy and Returns Policy pages.',
    limitationOfLiability: 'Limitation of Liability',
    limitationOfLiabilityDescription: 'IsaStore will not be liable for indirect, incidental, or consequential damages arising from the use of our products or services, beyond the value of the purchased product.',
    governingLaw: 'Governing Law',
    governingLawDescription: 'These terms of service are governed by the laws of the Republic of Costa Rica. Any disputes will be resolved in accordance with applicable Costa Rican legislation.',
    contactTerms: 'Contact Us About Terms',
    contactTermsText: 'If you have questions about these terms of service, contact us at:',

    // Admin - Password
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordChangedSuccess: 'Password changed successfully',
    errorChangingPassword: 'Error changing password',
    confirmDeleteProduct: 'Are you sure you want to delete this product?',
    productCreated: 'Product created successfully',
    productUpdated: 'Product updated successfully',
    productDeleted: 'Product deleted successfully',
    errorSavingProduct: 'Error saving product',
    errorDeletingProduct: 'Error deleting product',

    // Category Manager
    categoryManagement: 'Category Management',
    addCategory: 'Add Category',
    editCategory: 'Edit Category',
    addNewCategory: 'Add New Category',
    categoryIdPlaceholder: 'Category ID (e.g., Laptops)',
    englishName: 'English Name',
    spanishName: 'Spanish Name',
    categoryId: 'Category ID',
    errorSavingCategory: 'Error saving category',
    cannotDeleteCategory: 'Cannot delete "{name}" because it has {count} product(s). Please reassign or delete the products first.',
    confirmDeleteCategory: 'Are you sure you want to delete "{name}"?',
    errorDeletingCategory: 'Error deleting category',

    // Discount Manager - errors
    errorSavingDiscount: 'Error saving discount tier',
    errorDeletingDiscount: 'Error deleting discount tier',

    // Confirm clear cart
    confirmClearCart: 'Are you sure you want to clear the cart?',

    // Error Boundary
    errorBoundaryTitle: 'Something went wrong',
    errorBoundaryMessage: 'An unexpected error occurred. Please reload the page.',
    errorBoundaryReload: 'Reload Page',

    // Free server banner
    freeServerBanner: 'Server is waking up. Products may take ~10 seconds to load. If they don\'t load, please reload the page manually.',
    freeServerError: 'Could not connect to the server. This site uses a server that may be inactive. Please reload the page in a few seconds.',
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es') // Default to Spanish
  
  const t = (key, params = {}) => {
    try {
      if (!key) return ''
      if (!translations[language]) {
        console.warn(`Language '${language}' not found, defaulting to 'es'`)
        return translations['es'][key] || key
      }
      let translation = translations[language][key] || translations['es'][key] || key
      
      // Handle interpolation with params
      if (params && Object.keys(params).length > 0) {
        Object.keys(params).forEach(param => {
          translation = translation.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param])
        })
      }
      
      return translation
    } catch (error) {
      console.error('Translation error:', error, 'key:', key, 'language:', language)
      return key
    }
  }
  
  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es')
  }
  
  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}
