[phases.setup]
nixPkgs = ['...', 'postgresql']

[phases.install]
cmds = ['bundle install']

[phases.build]
cmds = [
  'bundle exec rails assets:precompile || true',
  'bundle exec rails assets:clean || true'
]

[start]
cmd = 'bash railway-deploy.sh'

