[phases.setup]
nixPkgs = ['...', 'postgresql']

[phases.install]
cmds = ['bundle install']

[phases.build]
cmds = [
  'bundle exec rails assets:precompile || true',
  'bundle exec rails assets:clean || true'
]

[phases.deploy]
cmds = ['bundle exec rails db:migrate']

[start]
cmd = 'bundle exec puma -C config/puma.rb'

