[phases.setup]
nixPkgs = ['...', 'postgresql']

[phases.install]
cmds = [
  'bundle config set --local deployment "true"',
  'bundle config set --local without "development test"',
  'bundle install --jobs=4 --retry=3'
]

[phases.build]
cmds = [
  # Skip asset precompilation for API-only app (saves time)
  'echo "Skipping asset precompilation (API-only app)"'
]

[start]
cmd = 'bash railway-deploy.sh'

