[phases.setup]
nixPkgs = ['...', 'postgresql']

[phases.install]
cmds = ['bundle install --without development test']

[phases.build]
cmds = [
  # Skip asset precompilation for API-only app (saves time)
  'echo "Skipping asset precompilation (API-only app)"'
]

[start]
cmd = 'bash railway-deploy.sh'

